# Generated by Django 6.0.1 on 2026-01-30 07:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='카테고리명')),
                ('icon', models.CharField(blank=True, max_length=10, verbose_name='아이콘')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='정렬순서')),
            ],
            options={
                'verbose_name': '카테고리',
                'verbose_name_plural': '카테고리 목록',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Memo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='메모 내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('keywords', models.CharField(blank=True, max_length=255, verbose_name='키워드 (자동 생성 예정)')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memos', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='memo.category', verbose_name='카테고리')),
            ],
            options={
                'verbose_name': '메모',
                'verbose_name_plural': '메모 목록',
                'ordering': ['-created_at'],
            },
        ),
    ]
