# Generated by Django 6.0.1 on 2026-01-30 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memo', '0002_alter_memo_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='카테고리명')),
                ('icon', models.CharField(blank=True, max_length=10, verbose_name='아이콘')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='정렬순서')),
            ],
            options={
                'verbose_name': '카테고리',
                'verbose_name_plural': '카테고리 목록',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='memo',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='memo.category', verbose_name='카테고리'),
        ),
    ]
