# Generated by Django 6.0.1 on 2026-01-30 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memo', '0005_seed_categories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memo',
            options={'ordering': ['-created_at'], 'verbose_name': '메모', 'verbose_name_plural': '메모들'},
        ),
        migrations.AlterField(
            model_name='memo',
            name='content',
            field=models.TextField(verbose_name='내용'),
        ),
        migrations.AlterField(
            model_name='memo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='작성일'),
        ),
        migrations.AlterField(
            model_name='memo',
            name='keywords',
            field=models.CharField(blank=True, max_length=255, verbose_name='키워드'),
        ),
        migrations.AlterField(
            model_name='memo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='수정일'),
        ),
    ]
