# Generated by Django 6.0.1 on 2026-01-30 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memo', '0006_alter_memo_options_alter_memo_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memo',
            name='keywords',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='키워드'),
        ),
    ]
